//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Boundary.com.arianpal.sandbox {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RequestPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyPaymentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Boundary.Properties.Settings.Default.Boundary_com_arianpal_sandbox_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RequestPaymentCompletedEventHandler RequestPaymentCompleted;
        
        /// <remarks/>
        public event verifyPaymentCompletedEventHandler verifyPaymentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PaymentRequestResult RequestPayment(string MerchantID, string Password, decimal Price, string Description, string Paymenter, string Email, string Mobile, string ResNumber, string ReturnPath) {
            object[] results = this.Invoke("RequestPayment", new object[] {
                        MerchantID,
                        Password,
                        Price,
                        Description,
                        Paymenter,
                        Email,
                        Mobile,
                        ResNumber,
                        ReturnPath});
            return ((PaymentRequestResult)(results[0]));
        }
        
        /// <remarks/>
        public void RequestPaymentAsync(string MerchantID, string Password, decimal Price, string Description, string Paymenter, string Email, string Mobile, string ResNumber, string ReturnPath) {
            this.RequestPaymentAsync(MerchantID, Password, Price, Description, Paymenter, Email, Mobile, ResNumber, ReturnPath, null);
        }
        
        /// <remarks/>
        public void RequestPaymentAsync(string MerchantID, string Password, decimal Price, string Description, string Paymenter, string Email, string Mobile, string ResNumber, string ReturnPath, object userState) {
            if ((this.RequestPaymentOperationCompleted == null)) {
                this.RequestPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestPaymentOperationCompleted);
            }
            this.InvokeAsync("RequestPayment", new object[] {
                        MerchantID,
                        Password,
                        Price,
                        Description,
                        Paymenter,
                        Email,
                        Mobile,
                        ResNumber,
                        ReturnPath}, this.RequestPaymentOperationCompleted, userState);
        }
        
        private void OnRequestPaymentOperationCompleted(object arg) {
            if ((this.RequestPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestPaymentCompleted(this, new RequestPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verifyPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VerifyPaymentResult verifyPayment(string MerchantID, string Password, decimal Price, string RefNum) {
            object[] results = this.Invoke("verifyPayment", new object[] {
                        MerchantID,
                        Password,
                        Price,
                        RefNum});
            return ((VerifyPaymentResult)(results[0]));
        }
        
        /// <remarks/>
        public void verifyPaymentAsync(string MerchantID, string Password, decimal Price, string RefNum) {
            this.verifyPaymentAsync(MerchantID, Password, Price, RefNum, null);
        }
        
        /// <remarks/>
        public void verifyPaymentAsync(string MerchantID, string Password, decimal Price, string RefNum, object userState) {
            if ((this.verifyPaymentOperationCompleted == null)) {
                this.verifyPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyPaymentOperationCompleted);
            }
            this.InvokeAsync("verifyPayment", new object[] {
                        MerchantID,
                        Password,
                        Price,
                        RefNum}, this.verifyPaymentOperationCompleted, userState);
        }
        
        private void OnverifyPaymentOperationCompleted(object arg) {
            if ((this.verifyPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyPaymentCompleted(this, new verifyPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentRequestResult {
        
        private string paymentPathField;
        
        private ResultValues resultStatusField;
        
        /// <remarks/>
        public string PaymentPath {
            get {
                return this.paymentPathField;
            }
            set {
                this.paymentPathField = value;
            }
        }
        
        /// <remarks/>
        public ResultValues ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ResultValues {
        
        /// <remarks/>
        Ready,
        
        /// <remarks/>
        GatewayUnverify,
        
        /// <remarks/>
        GatewayIsExpired,
        
        /// <remarks/>
        GatewayIsBlocked,
        
        /// <remarks/>
        GatewayInvalidInfo,
        
        /// <remarks/>
        UserNotActive,
        
        /// <remarks/>
        InvalidServerIP,
        
        /// <remarks/>
        Succeed,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyPaymentResult {
        
        private VerifyResult resultStatusField;
        
        private decimal payementedPriceField;
        
        /// <remarks/>
        public VerifyResult ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public decimal PayementedPrice {
            get {
                return this.payementedPriceField;
            }
            set {
                this.payementedPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum VerifyResult {
        
        /// <remarks/>
        Ready,
        
        /// <remarks/>
        NotMatchMoney,
        
        /// <remarks/>
        Verifyed,
        
        /// <remarks/>
        InvalidRef,
        
        /// <remarks/>
        GatewayInvalidInfo,
        
        /// <remarks/>
        Success,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RequestPaymentCompletedEventHandler(object sender, RequestPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentRequestResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentRequestResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void verifyPaymentCompletedEventHandler(object sender, verifyPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VerifyPaymentResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VerifyPaymentResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591